development:
  clients:
    default:
      database: false_alarm_dev
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: false_alarm_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %> # we are using MongoLab
      options:
        timeout: 15
        refresh_interval: 10
